# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-22 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Motivo', models.CharField(max_length=15)),
                ('Fecha', models.DateField(auto_now=True)),
                ('Diagnostico', models.CharField(max_length=1000)),
                ('ProximaVisita', models.DateField()),
                ('Costo', models.IntegerField()),
                ('EstadoDeCobro', models.CharField(max_length=1)),
                ('PacienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Pacientes')),
            ],
        ),
    ]
