# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-22 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=80)),
                ('Nit', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cobros',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('MontoTotal', models.FloatField()),
                ('Estado', models.CharField(max_length=1)),
                ('ClienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCobros',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=1)),
                ('CobroId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.Cobros')),
                ('PedidoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Pedidos')),
                ('VisitaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Visitas')),
            ],
        ),
    ]
