# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-15 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCompleto', models.CharField(max_length=80)),
                ('Dpi', models.CharField(max_length=15)),
                ('Genero', models.CharField(max_length=1)),
                ('EstadoCivil', models.CharField(max_length=1)),
                ('Direccion', models.CharField(max_length=80)),
                ('FechaNacimiento', models.DateField()),
                ('Telefono', models.CharField(max_length=8)),
                ('TipoSangre', models.CharField(max_length=1)),
                ('Responsable', models.CharField(max_length=80)),
                ('TelefonoResponsable', models.CharField(max_length=8)),
                ('NombreConyugue', models.CharField(max_length=80)),
                ('Escolaridad', models.CharField(max_length=1)),
                ('Ocupacion', models.CharField(max_length=80)),
                ('DpiResponsable', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
