# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-15 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PrecioVenta', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PrecioVenta', models.FloatField()),
                ('Estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('CompraId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Compras')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedidos',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PrecioModificado', models.FloatField()),
                ('Estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PrecioVenta', models.FloatField()),
                ('Cantidad', models.IntegerField(null=True)),
                ('Existencia', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FechaHora', models.DateTimeField(auto_now=True)),
                ('Monto', models.FloatField()),
                ('TipoPedido', models.CharField(choices=[('1', 'Interno'), ('2', 'Externo')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=5)),
                ('Nombre', models.CharField(max_length=80)),
                ('Marca', models.CharField(max_length=80)),
                ('Unidad', models.CharField(choices=[('1', 'Unidad'), ('2', 'Caja')], default='1', max_length=1)),
                ('Cantidad', models.IntegerField(blank=True)),
                ('Precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=80)),
                ('Direccion', models.CharField(max_length=80)),
                ('Telefono', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='lotes',
            name='ProductoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.Productos'),
        ),
        migrations.AddField(
            model_name='detallepedidos',
            name='LoteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Lotes'),
        ),
        migrations.AddField(
            model_name='detallepedidos',
            name='PedidoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Pedidos'),
        ),
        migrations.AddField(
            model_name='detallecompras',
            name='LoteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Lotes'),
        ),
        migrations.AddField(
            model_name='compras',
            name='ProductoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Productos'),
        ),
    ]
