# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompras',
            name='Estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='detallepedidos',
            name='Estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Unidad',
            field=models.CharField(choices=[('1', 'Unidad'), ('2', 'Caja')], default='1', max_length=1),
        ),
    ]
