# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
