# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-27 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180620_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='ProductoId',
        ),
        migrations.RemoveField(
            model_name='detallecompras',
            name='CompraId',
        ),
        migrations.RemoveField(
            model_name='detallecompras',
            name='LoteId',
        ),
        migrations.AddField(
            model_name='detallepedidos',
            name='Cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallepedidos',
            name='PrecioModificado',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='TipoPedido',
            field=models.CharField(choices=[('1', 'Interno'), ('2', 'Externo')], default='2', max_length=1),
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='DetalleCompras',
        ),
    ]
