# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-30 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180524_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Existencia',
            field=models.IntegerField(default=0),
        ),
    ]
