# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-19 22:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180626_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotes',
            name='FechaIngreso',
            field=models.DateField(auto_now=True, default=datetime.datetime(2018, 7, 19, 22, 51, 40, 235780, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallepedidos',
            name='PedidoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Pedidos'),
        ),
    ]
