# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-03 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180530_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='Existencia',
        ),
        migrations.AddField(
            model_name='lotes',
            name='Cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='ProductoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.Productos'),
        ),
    ]
